---
- name: Build Frontend
  hosts: local
  vars:
    frontend_root: ../../frontend
  tasks:
    - name: Install Node.js dependencies
      command: npm install
      args:
        chdir: "{{ frontend_root }}"

    - name: Build Frontend
      command: npm run build
      args:
        chdir: "{{ frontend_root }}"
      environment:
        VITE_API_BASE_URL: "http://100.30.240.77/api"

- name: Deploy Frontend to EC2
  hosts: webservers
  become: yes
  vars:
    frontend_root: ../../frontend
  tasks:
    - name: Ensure nginx html dir
      file:
        path: /usr/share/nginx/html
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy dist to nginx
      synchronize:
        src: "{{ frontend_root }}/dist/"
        dest: /usr/share/nginx/html/
        delete: yes
        archive: no
        recursive: yes
        rsync_path: "sudo rsync"
      delegate_to: localhost
      become: no
