[local]
localhost ansible_connection=local

[webservers]
[webservers]
54.165.0.228 ansible_user=ec2-user ansible_ssh_private_key_file=../ticket-analyzer-dev-key-v2.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_python_interpreter=/usr/bin/python3
